version: "3.8"

services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      - "POSTGRES_DB=${PSQL_DB}"
      - "POSTGRES_USER=${PSQL_USER}"
      - "POSTGRES_PASSWORD=${PSQL_PASSWORD}"
    networks:
      - overlay
    ports:
      - "${PSQL_PORT}:5432"

networks:
  overlay:

