version: "3.8"

services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      - "POSTGRES_DB=${DB_NAME}"
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
    networks:
      - overlay
    ports:
      - "${DB_PORT}:5432"

networks:
  overlay:

